// src/resources/cosai-mapping.ts

export const COSAI_MCP_SECURITY_MAPPING = {
  title: 'AGA Coverage of CoSAI MCP Security Threat Taxonomy',
  source: 'Coalition for Secure AI (CoSAI), OASIS Open Project',
  whitepaper: 'Securing the AI Agent Revolution: A Practical Guide to Model Context Protocol Security',
  published: 'January 20, 2026',
  url: 'https://github.com/cosai-oasis/ws4-secure-design-agentic-systems/blob/main/model-context-protocol-security.md',

  categories: [
    {
      id: 'T1',
      name: 'Improper Authentication',
      domain: 'Foundational Identity & Access',
      cosai_description: 'Weak identity verification and credential management across agent chains',
      aga_tools: ['aga_create_artifact', 'aga_verify_artifact', 'aga_rotate_keys'],
      aga_mechanism: 'Ed25519 artifact signatures verified against pinned issuer public key. Portal rejects artifacts with invalid signatures. Key rotation recorded as chain events with both old and new keys for transition period. TTL-based re-attestation enforces continuous authentication.',

      nist_ref: 'NCCoE Section 3: Authentication',
    },
    {
      id: 'T2',
      name: 'Missing Access Control',
      domain: 'Foundational Identity & Access',
      cosai_description: 'Insufficient authorization checks and privilege separation',
      aga_tools: ['aga_start_monitoring', 'aga_trigger_measurement', 'aga_delegate_to_subagent'],
      aga_mechanism: 'Portal enforces sealed policy constraints as a mandatory interception layer. Agent holds no credentials and cannot bypass the portal. Delegation enforces scope diminishment: child scope must be a strict subset of parent. TTL inheritance prevents privilege extension through delegation.',
      nist_ref: 'NCCoE Section 4: Authorization, CAISI Section 4a',
    },
    {
      id: 'T3',
      name: 'Input Validation Failures',
      domain: 'Input Handling',
      cosai_description: 'Traditional injection flaws amplified by AI mediation',
      aga_tools: ['aga_trigger_measurement', 'aga_measure_behavior'],
      aga_mechanism: 'Portal validates every operation against sealed artifact parameters before authorizing execution. Behavioral drift detection monitors tool invocation patterns against a sealed baseline, catching injection-driven anomalies independent of binary integrity.',
      nist_ref: 'CAISI Section 1a: Semantic Drift Without Binary Modification',
    },
    {
      id: 'T4',
      name: 'Data/Control Boundary Failures',
      domain: 'Input Handling',
      cosai_description: 'Prompt injection and tool poisoning exploiting the LLM as intermediary',
      aga_tools: ['aga_measure_behavior', 'aga_quarantine_status'],
      aga_mechanism: 'Behavioral baseline sealed in artifact defines permitted tools, forbidden sequences, and rate limits. Prompt injection that causes unauthorized tool invocations or forbidden sequences triggers enforcement. Phantom execution quarantines the compromised agent while capturing the full attack sequence as signed forensic evidence.',
      nist_ref: 'NCCoE Section 6: Prompt Injection Prevention and Mitigation',
    },
    {
      id: 'T5',
      name: 'Inadequate Data Protection',
      domain: 'Data & Code Protection',
      cosai_description: 'Insufficient encryption and secrets management',
      aga_tools: ['aga_create_artifact', 'aga_disclose_claim'],
      aga_mechanism: 'Attestation evidence stored as salted commitments: Hash(Content || Salt). Original content never stored in the artifact. Privacy-preserving disclosure with automatic substitution prevents sensitive data exposure. Inference risk checking blocks combinations of disclosures that would reveal denied claims.',
      nist_ref: 'CAISI Section 5a: Privacy-Preserving Governance Disclosure',
    },
    {
      id: 'T6',
      name: 'Missing Integrity Controls',
      domain: 'Data & Code Protection',
      cosai_description: 'Lack of verification for MCP servers and tool definitions',
      aga_tools: ['aga_create_artifact', 'aga_trigger_measurement', 'aga_verify_artifact'],
      aga_mechanism: 'Sealed hash computed over subject bytes, metadata, policy reference, and salt. Portal computes runtime hash on every request and compares to sealed reference. Any modification to any component (server binary, tool definitions, configuration) produces a hash mismatch and triggers enforcement. 10 measurement embodiments cover executable images, loaded modules, container images, configuration manifests, SBOMs, and more.',
      nist_ref: 'CAISI Section 2a: Sealed Policy Artifacts',
    },
    {
      id: 'T7',
      name: 'Session/Transport Security',
      domain: 'Network & Transport',
      cosai_description: 'Insecure protocols and session management',
      aga_tools: ['aga_create_artifact', 'aga_revoke_artifact'],
      aga_mechanism: 'Artifact TTL enforces session expiration. Expired artifacts require re-attestation (fail-closed). Mid-session revocation immediately terminates agent authority. All artifacts and receipts cryptographically signed with Ed25519, preventing session hijacking or replay.',
      nist_ref: 'NCCoE Section 3: TTL-Based Re-Attestation',
    },
    {
      id: 'T8',
      name: 'Network Isolation Failures',
      domain: 'Network & Transport',
      cosai_description: 'Improper network binding and segmentation',
      aga_tools: ['aga_start_monitoring', 'aga_trigger_measurement'],
      aga_mechanism: 'Two-process architecture: portal and agent are separate OS processes. Agent has no direct network access, no credentials, no keys. Portal is the only path to external resources. NETWORK_ISOLATE enforcement action severs network connections while allowing continued local execution for forensic capture.',
      nist_ref: 'CAISI Section 2a: The Portal as Mandatory Runtime Enforcement Boundary',
    },
    {
      id: 'T9',
      name: 'Trust Boundary Failures',
      domain: 'Trust & Design',
      cosai_description: 'Overreliance on LLM judgment for security decisions',
      aga_tools: ['aga_create_artifact', 'aga_trigger_measurement', 'aga_measure_behavior'],
      aga_mechanism: 'Security decisions are pre-committed in the sealed artifact by human authorities before deployment, not delegated to the LLM at runtime. The portal enforces constraints mechanically through hash comparison and behavioral pattern matching. The LLM cannot override, modify, or bypass the sealed enforcement parameters.',
      nist_ref: 'CAISI Section 4a: Fail-Closed Semantics',
    },
    {
      id: 'T10',
      name: 'Resource Management',
      domain: 'Trust & Design',
      cosai_description: 'Absence of rate limiting and quota controls',
      aga_tools: ['aga_measure_behavior', 'aga_create_artifact'],
      aga_mechanism: 'Behavioral baseline includes per-tool rate limits sealed in the artifact. Portal tracks invocation rates within a configurable time window. Rate limit violations trigger enforcement. Measurement cadence is configurable from 10ms (SCADA) to 3,600,000ms, preventing resource exhaustion from excessive measurement overhead.',
      nist_ref: 'CAISI Section 2a: Configurable Measurement Cadences',
    },
    {
      id: 'T11',
      name: 'Supply Chain Failures',
      domain: 'Operational Security',
      cosai_description: 'Insecure MCP server lifecycle and distribution',
      aga_tools: ['aga_create_artifact', 'aga_verify_artifact', 'aga_trigger_measurement'],
      aga_mechanism: 'Content-addressable hash binding at attestation time. Every component (server binary, skill files, dependencies, configuration) is hashed and sealed into the artifact. Runtime measurement detects any modification to any component. Artifact signature binds all fields cryptographically. Modified or substituted components produce hash mismatches and are blocked before execution.',
      nist_ref: 'CAISI Section 1a: Supply Chain Injection',
    },
    {
      id: 'T12',
      name: 'Insufficient Observability',
      domain: 'Operational Security',
      cosai_description: 'Lack of logging, monitoring, and audit trails',
      aga_tools: ['aga_generate_receipt', 'aga_get_chain', 'aga_export_bundle', 'aga_verify_bundle'],
      aga_mechanism: 'Signed receipt generated for every measurement (match or mismatch). Receipts appended to tamper-evident continuity chain linked by structural metadata hashes. Payload excluded from leaf hash computation, enabling third-party verification without payload disclosure. Merkle checkpoint anchoring prevents history rewriting. Evidence bundles enable portable offline verification through a 4-step process: artifact signature, receipt signatures, Merkle proofs, and anchor validation.',
      nist_ref: 'CAISI Section 2a: Tamper-Evident Accountability',
    },
  ],
};

// Summary statistics
export const COSAI_COVERAGE_SUMMARY = {
  total_threat_categories: 12,
  categories_with_aga_coverage: 12,
  total_tools_referenced: 20,  // all 20 tools participate in at least one category
  unique_cosai_categories_covered: 12,
  nist_submission_sections_referenced: 10,
};
